MeasureAuthoringTool/measure-service

- src/main/java/cms/gov/madie/measure/models/Measure.java
Model identifies the Data Model (FHIR, QI-Core, QDM, etc.) used in the measure.
> [MAT-3531] Add model property to Measure model

- pom.xml
- src/main/java/cms/gov/madie/measure/SpringFoxConfig.java
- src/main/java/cms/gov/madie/measure/models/Measure.java
- src/main/java/cms/gov/madie/measure/models/MeasureMetaData.java
- src/main/java/cms/gov/madie/measure/resources/MeasureController.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerMvcTest.java
> MAT-3513 Save/Update measure's steward

- pom.xml
update log4j for CVE-2021-45104
> update log4j for CVE-2021-45104

- src/main/java/cms/gov/madie/measure/models/Measure.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerMvcTest.java
Added a condition to verify if the measure name has atleast one letter.
> Added a condition to check for atleast one letter in measure name

- src/main/resources/application.yml
Jira Ticket: [MAT-3810](https://jira.cms.gov/browse/MAT-3810)
> adding okta audience as parameterized; ref #MAT-3810

- src/main/java/cms/gov/madie/measure/models/Measure.java
- src/main/java/cms/gov/madie/measure/repositories/MeasureRepository.java
- src/main/java/cms/gov/madie/measure/resources/MeasureController.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerTest.java
Jira Ticket: [MAT-3812](https://jira.cms.gov/browse/MAT-3812)
> add query param to filter getMeasures by current user; ref #MAT-3812

- src/main/java/cms/gov/madie/measure/resources/TestCaseController.java
- src/main/java/cms/gov/madie/measure/services/TestCaseService.java
- src/test/java/cms/gov/madie/measure/resources/TestCaseControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/TestCaseControllerTest.java
Jira Ticket: [MAT-3746](https://jira.cms.gov/browse/MAT-3746)
New Endpoints:
- GET: /measures/{measureId}/test-cases/{testCaseId}
Retrieve the Test Case with testCaseId embeded within the Measure document with ID measureId.
- PUT: /measures/{measureId}/test-cases/{testCaseId}
Replace the existing Test Case with the provided Test Case data.  …
> Add endpoints for fetching and updating a Test Case

- .gitignore
- src/main/java/cms/gov/madie/measure/models/Measure.java
- src/main/java/cms/gov/madie/measure/models/TestCase.java
- src/main/java/cms/gov/madie/measure/repositories/MeasureRepository.java
- src/main/java/cms/gov/madie/measure/resources/TestCaseController.java
- src/main/java/cms/gov/madie/measure/services/TestCaseService.java
- src/test/java/cms/gov/madie/measure/resources/TestCaseControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/TestCaseControllerTest.java
- src/test/java/cms/gov/madie/measure/service/TestCaseServiceTest.java
Jira Ticket: [MAT-3861](https://jira.cms.gov/browse/MAT-3861)
Backend changes to support fetching distinct list of series from test cases on a given measure
> new endpoint to fetch distinct test case series for a given measure

- src/main/java/cms/gov/madie/measure/models/TestCase.java
- src/test/java/cms/gov/madie/measure/resources/TestCaseControllerMvcTest.java
Jira Ticket: [MAT-3854](https://jira.cms.gov/browse/MAT-3854)
> Mat-3854, test case title backend

- src/main/java/cms/gov/madie/measure/models/TestCase.java
- src/test/java/cms/gov/madie/measure/resources/TestCaseControllerMvcTest.java
Jira Ticket: [MAT-3835](https://jira.cms.gov/browse/MAT-3835)
Placeholder property for Test Case JSON data.
> [MAT-3835] Add JSON property to Test Case Model (placeholder in lieu of HAPI FHIR)

- src/main/java/cms/gov/madie/measure/SecurityConfig.java
Jira Ticket: [MAT-3810](https://jira.cms.gov/browse/MAT-3810)
> white list health check

- src/main/java/cms/gov/madie/measure/exceptions/InvalidIdException.java
- src/main/java/cms/gov/madie/measure/resources/ErrorHandlingControllerAdvice.java
- src/main/java/cms/gov/madie/measure/resources/MeasureController.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerTest.java
Jira Ticket: [MAT-3892](https://jira.cms.gov/browse/MAT-3892)
> add measure ID to PUT measure call uri; ref #MAT-3892

- src/main/java/cms/gov/madie/measure/exceptions/InvalidIdException.java
- src/main/java/cms/gov/madie/measure/resources/TestCaseController.java
- src/main/java/cms/gov/madie/measure/utils/UserInputSanitizeUtil.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerTest.java
- src/test/java/cms/gov/madie/measure/utils/UserInputSanitizeUtilTest.java
Jira Ticket: [MAT-3960](https://jira.cms.gov/browse/MAT-3960)
> MAT-3960 remove html characters due to sanitizing data

- src/main/java/cms/gov/madie/measure/models/TestCase.java
- src/main/java/cms/gov/madie/measure/resources/TestCaseController.java
- src/test/java/cms/gov/madie/measure/resources/TestCaseControllerMvcTest.java
Jira Ticket: [MAT-3961](https://jira.cms.gov/browse/MAT-3961)
(Optional) Related Tickets: https://jira.cms.gov/browse/MAT-3890, https://jira.cms.gov/browse/MAT-3898
> MAT-3890, MAT-3898 and MAT-3961

- src/main/java/cms/gov/madie/measure/SecurityConfig.java
- src/main/java/cms/gov/madie/measure/models/MeasureMetaData.java
- src/test/java/cms/gov/madie/measure/model/MeasureSerializationTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerTest.java
Jira Ticket: [MAT-3565](https://jira.cms.gov/browse/MAT-3565)
> Mat 3565 metadata description

- src/main/java/cms/gov/madie/measure/HapiFhirConfig.java
- src/main/java/cms/gov/madie/measure/services/TestCaseService.java
Jira Ticket: [MAT-3864](https://jira.cms.gov/browse/MAT-3864)
> HAPI integration prop fix; ref #MAT-3864

- src/main/java/cms/gov/madie/measure/models/MeasureMetaData.java
- src/test/java/cms/gov/madie/measure/model/MeasureSerializationTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerTest.java
Jira Ticket: [MAT-3572](https://jira.cms.gov/browse/MAT-3572)
> MAT-3572 meta data copyright

- src/main/java/cms/gov/madie/measure/models/MeasureMetaData.java
- src/test/java/cms/gov/madie/measure/model/MeasureSerializationTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerTest.java
Jira Ticket: [MAT-3581](https://jira.cms.gov/browse/MAT-3581)
> MAT-3581 meta data disclaimer

- src/main/java/cms/gov/madie/measure/models/MeasureScoring.java
- src/main/java/cms/gov/madie/measure/models/TestCase.java
- src/main/java/cms/gov/madie/measure/models/TestCaseGroupPopulation.java
- src/main/java/cms/gov/madie/measure/models/TestCasePopulationValue.java
- src/main/java/cms/gov/madie/measure/utils/ScoringPopulationDefinition.java
- src/main/java/cms/gov/madie/measure/validations/ScoringPopulationValidator.java
- src/main/java/cms/gov/madie/measure/validations/ValidScoringPopulation.java
- src/test/java/cms/gov/madie/measure/resources/TestCaseControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/validations/ScoringPopulationValidatorTest.java
Jira Ticket: [MAT-3889](https://jira.cms.gov/browse/MAT-3889)
> persist and validate test case population values; ref #MAT-3889

- src/main/java/cms/gov/madie/measure/MeasureServiceApplication.java
- src/main/java/cms/gov/madie/measure/models/TestCase.java
- src/main/java/cms/gov/madie/measure/models/TestCasePopulationValue.java
- src/main/java/cms/gov/madie/measure/utils/ScoringPopulationDefinition.java
- src/main/java/cms/gov/madie/measure/validations/ScoringPopulationValidator.java
- src/main/java/cms/gov/madie/measure/validations/ValidScoringPopulation.java
- src/test/java/cms/gov/madie/measure/validations/ScoringPopulationValidatorTest.java
Jira Ticket: [MAT-4509](https://jira.cms.gov/browse/MAT-4509)
Just adding Test & Impl to Cross Origin exceptions
> MAT-4059: Adding impl & test for CrossOrigin exceptions

- src/main/java/cms/gov/madie/measure/repositories/MeasureRepository.java
- src/main/java/cms/gov/madie/measure/resources/MeasureController.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerTest.java
Jira Ticket: [MAT-3942](https://jira.cms.gov/browse/MAT-3942)
Allow the /measures route to return Page documents to allow for paginated request of measure lists
> MAT-3942: Measure Service Page Requests

- src/main/java/cms/gov/madie/measure/validations/ScoringPopulationValidator.java
- src/test/java/cms/gov/madie/measure/validations/ScoringPopulationValidatorTest.java
Jira Ticket: [MAT-0000](https://jira.cms.gov/browse/MAT-0000)
> fix for broken create test cases

- src/main/java/cms/gov/madie/measure/SecurityConfig.java
- src/main/java/cms/gov/madie/measure/resources/MeasureController.java
- src/main/java/cms/gov/madie/measure/resources/MeasureTransferController.java
- src/main/java/cms/gov/madie/measure/services/MeasureService.java
- src/main/resources/application.yml
- src/test/java/cms/gov/madie/measure/resources/MeasureControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureTransferControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/resources/MeasureTransferControllerTest.java
- src/test/java/cms/gov/madie/measure/validations/GroupScoringPopulationValidatorTest.java
Jira Ticket: [MAT-3965](https://jira.cms.gov/browse/MAT-3965)
- added separete endpoint for measure transfer
> MAT-3965 Use Lambda to Pass Transferred Measure to Measure-Service

- src/main/java/cms/gov/madie/measure/resources/MeasureTransferController.java
Jira Ticket: [MAT-3965](https://jira.cms.gov/browse/MAT-3965)
Missed to assign group ids when saving measure from lambda. This fix adds the id for measure group 
> MAT-3965 groups need to have mongo ids

- src/main/java/cms/gov/madie/measure/HapiFhirConfig.java
- src/main/java/cms/gov/madie/measure/models/Measure.java
- src/main/java/cms/gov/madie/measure/models/TestCase.java
- src/main/java/cms/gov/madie/measure/resources/MeasureController.java
- src/main/java/cms/gov/madie/measure/resources/MeasureTransferController.java
- src/main/java/cms/gov/madie/measure/services/TestCaseService.java
- src/main/resources/application.yml
- src/test/java/cms/gov/madie/measure/resources/MeasureTransferControllerMvcTest.java
- src/test/java/cms/gov/madie/measure/service/TestCaseServiceTest.java
Jira Ticket: [MAT-3949](https://jira.cms.gov/browse/MAT-3949)
Test Case JSON is currently expected to conform to FHIR4 Bundle validations containing a Patient Resource. Replacing Patient validations/upserts to HAPI with Bundle.
Persist the generated ELM JSON so it can be retrieved by the Test Case app for passing to the measure execution engine.
Set default Measurement Period (date only) to the next calendar year when creating a new measure. Needed for measure calculation in Test Case app.
- Does not handle updating existing measures. Currently, the date pickers are read-only due to issues with data syncing. Once resolved, the MP will be able to be set on the Test Case List page.
- Eventually, we will need to increase the precision on the MP as users will want …
> [MAT-3949] Persist Generated ELM JSON and Set Default MP on New Measures
